### ISSUE TITLE
trouble installing - Symbol not found: _GOMP_parallel

### ISSUE THREAD

**Issue by shaharkadmiel** [pyrocko/kite#43]
I've cloned the repo and tried installing with `python setup.py install`, `pip install -e .`, `pip install .`.

Installation is successful but when I `import kite` I get:

```python
ImportError                               Traceback (most recent call last)
<ipython-input-2-366e0b4292fe> in <module>
----> 1 import kite

~/miniconda3/lib/python3.7/site-packages/kite/__init__.py in <module>
      2 import pkg_resources
      3 
----> 4 from .scene import Scene, TestScene, read  # noqa
      5 from .quadtree import Quadtree  # noqa
      6 from .covariance import Covariance  # noqa

~/miniconda3/lib/python3.7/site-packages/kite/scene.py in <module>
     10 
     11 from kite.quadtree import QuadtreeConfig
---> 12 from kite.covariance import CovarianceConfig
     13 from kite.util import Subject, property_cached
     14 from kite import scene_io

~/miniconda3/lib/python3.7/site-packages/kite/covariance.py in <module>
      5 import time
      6 
----> 7 from kite import covariance_ext
      8 from pyrocko import guts
      9 from pyrocko.guts_array import Array

ImportError: dlopen(/Users/shahar/miniconda3/lib/python3.7/site-packages/kite/covariance_ext.cpython-37m-darwin.so, 2): Symbol not found: _GOMP_parallel
  Referenced from: /Users/shahar/miniconda3/lib/python3.7/site-packages/kite/covariance_ext.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/shahar/miniconda3/lib/python3.7/site-packages/kite/covariance_ext.cpython-37m-darwin.so
```

I am on macOSv10.12.6 with anaconda3.

**Comment by miili** [comment]
Hi Sahar,

it appears your exotic MacOS has OpenMP libraries. I fixed the `setup.py` and added approriate linker arguments.
I don't have a MacOS like yours at hand atm. Could you install again from the `dev` branch and let me know if the library is linking correctly now?
```
pip install git+https://github.com/pyrocko/kite.git@dev
```
Best,
Marius

**Comment by shaharkadmiel** [comment]
Hi Marius,
Thanks for your efforts.

I am not using the `clang` compilers of the OS. I have GCC and Intel compilers installed. Looking at the `setup.py` script, I see the `-rpath` is hardcoded which can be problematic. I changed it to reflect my gcc libs location but I still get the same error.

It would be better to use the `library_dirs` and `libraries` keywords of the `Extension` class with some temporarily set environment variables.

I also tried turning the use of OpenMP off by making the `_have_openmp()` fail but I still get the same error.

I also suggest moving to numpy distutils for `setup()` with `ext_modules`.

Cheers,
Shahar

**Comment by miili** [comment]
Hi Sahar,
did you remove the `build` and `dist` directories to force compilation? when `_have_openmp()` is negative all OpenMP dependencies should be neglected.
Where do you see an advantage of NumPy's distutils? From my experience it is only useful for Fortran libraries. The simple extension in kite is usually building without problems.

Feel free to contact me on the hive `https://hive.pyrocko.org`.

**Comment by shaharkadmiel** [comment]
I suggest a change to the `setup.py` in https://github.com/shaharkadmiel/kite/tree/patch-1
It now works for me.

**Comment by miili** [comment]
Deear Shahar, can you confirm the updated PR?
